
#{{ title }} 

```{r, include=FALSE}
pdat = dat[["{{ sub }}"]]
pdat = pdat[!is.na(pdat[["{{ iv1 }}"]]) & !is.na(pdat[["{{ iv2 }}"]]),]
pdat = tryCatch(remove_group_data(pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}")), error = function(e) NULL)

if (!is.null(pdat)) {
  pwc = ancova.pwc(pdat, "{{ dv }}", c("{{ iv2 }}","{{ iv1 }}"), "{{ covar }}", pwc.covar=T)
  (apa <- get.ancova.emmeans.with.ds(pwc, pdat, "{{ dv }}", c("{{ iv2 }}","{{ iv1 }}"), "apa-format", covar = "{{ covar }}"))
}
```

```{r, echo=FALSE, purl=FALSE}
if (!is.null(pdat))
  kable(apa, digits = 3)
```

```{r, include=FALSE}
if (!is.null(pdat)) {
  pdf <- get.ancova.pwc.table(pwc, only.sig = F)
  (pdf <- pdf[!is.na(pdf$p.adj),])
}
```

```{r, echo=FALSE, purl=FALSE}
if (!is.null(pdat)) {
  pdf <- round.pval(pdf)
  kable(pdf[,c("{{ iv1 }}","{{ iv2 }}","group1","group2","estimate","conf.low",
               "conf.high","se","statistic","p","p.adj","p.adj.signif")], digits = 3)
}
```


```{r, include=FALSE}
if (!is.null(pdat)) {
  pdat.long = dat.long[["{{ sub }}"]]
  pdat.long = pdat.long[!is.na(pdat.long[["{{ iv1 }}"]]) & !is.na(pdat.long[["{{ iv2 }}"]]),]
  pdat.long = remove_group_data(pdat.long, "{{ pivot.value }}", c("{{ pivot.key }}","{{ iv1 }}","{{ iv2 }}"))
  
  pwc.long = anova.pwc(pdat.long, "{{ pivot.value }}", c("{{ pivot.key }}","{{ iv1 }}","{{ iv2 }}"))
  pwc.long = pwc.long${{ pivot.value }}${{ pivot.key }}
  (pdf.long <- pwc.long[!is.na(pwc.long$p.adj),])
}
```

```{r, echo=FALSE, purl=FALSE}
if (!is.null(pdat)) {
  pdf.long <- round.pval(pdf.long)
  kable(pdf.long[,c("{{ iv1 }}","{{ iv2 }}","group1","group2","estimate","conf.low",
                    "conf.high","se","statistic","p","p.adj","p.adj.signif")], digits = 3)
}
```

```{r}
if (!is.null(pdat))
  plots <- twoWayAncovaPlots(pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"), {{ aov }}, pwc${{ dv }},
                             addParam = c("jitter"), font.label.size=10,
                             step.increase=0.05, p.label="p.adj",
                             subtitle = which({{ aov }}$Effect == "{{ iv1 }}:{{ iv2 }}"))
```

```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
if (!is.null(pdat) && !is.null(nrow(plots[["{{ iv1 }}"]]$data)))
  plots[["{{ iv1 }}"]] + ggplot2::scale_color_manual(values = color[["{{ sub }}"]][["{{ iv2 }}"]])
```


```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
if (!is.null(pdat) && !is.null(nrow(plots[["{{ iv2 }}"]]$data)))
  plots[["{{ iv2 }}"]] + ggplot2::scale_color_manual(values = color[["{{ sub }}"]][["{{ iv1 }}"]])
```


```{r}
if ({{ barplot }} && !is.null(pdat))
  plots <- twoWayAncovaBarPlots(
    pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"), {{ aov }}, pwc${{ dv }}, covar = "{{ covar }}",
    theme = "classic", color = color[["{{ sub }}"]][["{{ iv1 }}:{{ iv2 }}"]],
    subtitle = which({{ aov }}$Effect == "{{ iv1 }}:{{ iv2 }}"))
```

```{r, dpi=300, fig.width={{ fig.width.bar }}, fig.height={{ fig.height.bar }}}
if ({{ barplot }} && !is.null(pdat))
  plots[["{{ iv1 }}:{{ iv2 }}"]] + ggplot2::ylab("{{ ylab }}") + ggplot2::scale_x_discrete(labels=c('pre', 'pos'))
```

```{r}
if (!is.null(pdat))
  plots <- twoWayAncovaBoxPlots(
    pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"), {{ aov }}, pwc${{ dv }}, covar = "{{ covar }}",
    theme = "classic", color = color[["{{ sub }}"]][["{{ iv1 }}:{{ iv2 }}"]],
    subtitle = which({{ aov }}$Effect == "{{ iv1 }}:{{ iv2 }}"))
```

```{r, dpi=300, fig.width={{ fig.width.bar }}, fig.height={{ fig.height.bar }}}
if (!is.null(pdat))
  plots[["{{ iv1 }}:{{ iv2 }}"]] + ggplot2::ylab("{{ ylab }}") + ggplot2::scale_x_discrete(labels=c('pre', 'pos'))
```

```{r}
if (!is.null(pdat))
  plots <- twoWayAncovaBoxPlots(
    pdat.long, "{{ pivot.value }}", c("{{ iv1 }}","{{ iv2 }}"), {{ aov }}, pwc.long, pre.post = "{{ pivot.key }}",
    theme = "classic", color = color[["{{ sub }}"]]$prepost)
```

```{r, dpi=300, fig.width={{ fig.width.pbar }}, fig.height={{ fig.height.pbar }}}
if (!is.null(pdat))
  plots[["{{ iv1 }}:{{ iv2 }}"]] + ggplot2::ylab("{{ ylab }}")
```

